spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joream?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: root
  #  datasource:
##    url: jdbc:h2:tcp://localhost/~/springbootproject
##    username: sa
##    password:
##    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  secret: joreamjoreamjoreamjoreamjoreamjoreamjoream
  expiration: 60000000