spring:
  datasource:
    url: jdbc:mysql://localhost:3306/joream?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  secret: joreamjoreamjoreamjoreamjoreamjoreamjoream
  expiration: 600000