spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/springbootproject
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  secret: joreamjoreamjoreamjoreamjoreamjoreamjoream
  expiration: 60000000